services:
  postgres:
    image: postgres
    container_name: hrm-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: hrm-api
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    ports:
      - "${API_PORT}:8000"
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: hrm-frontend
    env_file:
      - .env
    restart: always
    depends_on:
      - api
    ports:
      - "5173:5173"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: hrm-bot
    env_file:
      - .env
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres_data:
